/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveillanceRouteImport } from './routes/surveillance'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as DiseaseRouteImport } from './routes/disease'
import { Route as IndexRouteImport } from './routes/index'

const SurveillanceRoute = SurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseRoute = DiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/parcels': typeof ParcelsRoute
  '/satellite': typeof SatelliteRoute
  '/surveillance': typeof SurveillanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/parcels': typeof ParcelsRoute
  '/satellite': typeof SatelliteRoute
  '/surveillance': typeof SurveillanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disease': typeof DiseaseRoute
  '/parcels': typeof ParcelsRoute
  '/satellite': typeof SatelliteRoute
  '/surveillance': typeof SurveillanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disease' | '/parcels' | '/satellite' | '/surveillance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disease' | '/parcels' | '/satellite' | '/surveillance'
  id:
    | '__root__'
    | '/'
    | '/disease'
    | '/parcels'
    | '/satellite'
    | '/surveillance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiseaseRoute: typeof DiseaseRoute
  ParcelsRoute: typeof ParcelsRoute
  SatelliteRoute: typeof SatelliteRoute
  SurveillanceRoute: typeof SurveillanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surveillance': {
      id: '/surveillance'
      path: '/surveillance'
      fullPath: '/surveillance'
      preLoaderRoute: typeof SurveillanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease': {
      id: '/disease'
      path: '/disease'
      fullPath: '/disease'
      preLoaderRoute: typeof DiseaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiseaseRoute: DiseaseRoute,
  ParcelsRoute: ParcelsRoute,
  SatelliteRoute: SatelliteRoute,
  SurveillanceRoute: SurveillanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
